export let items = {
    Data: [
        {
            id: 1,
            title: 'iPhone 12',
            img: '12.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A15.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0513x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A15 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 22 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
  
        },

        {
            id: 2,
            title: 'iPhone 12 Pro',
            img: '12pro.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A14.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0512x.png',
            icons: 'display|A14|triplecamera|5g|faceid|battery|lightning|0513x',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A14 Bionic chip  /  6-core CPU / 4-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 17 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.29 inch (7.4 mm);Weight;6.66 ounces (189 grams)',
        },
        {
            id: 3,
            title: 'iPhone 12 Pro Max',
            img: '12promax.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A15.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0513x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A15 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 22 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
        },
        {
            id: 4,
            title: 'iPhone 13',
            img: '13.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A15.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0513x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A15 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 22 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
  
        },
        {
            id: 5,
            title: 'iPhone 13 Pro',
            img: '13pro.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A15.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0513x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A15 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 22 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
        },
        {
            id: 6,
            title: 'iPhone 13 Pro Max',
            img: '13promax.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A15.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0513x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A15 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 22 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
  
        },
        {
            id: 7,
            title: 'iPhone 14',
            img: '14.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A15.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0513x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A15 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 22 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
  
        },
        {
            id: 8,
            title: 'iPhone 14 Pro',
            img: '14pro.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A16.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '05123x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A16 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /48MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 23s hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.81 inches (147.5 mm);Width;2.81 inches (71.5 mm);Depth;0.31 inch (7.85 mm);Weight;7.27 ounces (206 grams)',
        },
        {
            id: 9,
            title: 'iPhone 14 Pro Max',
            img: '14promax.png',
            category: 'iPhone',
            firstParam: 'display.png',
            secondParam: 'A15.png',
            thirdParam: 'triplecamera.png',
            fourthParam: '5g.png',
            fifthParam: 'faceid.png',
            sixthParam: 'battery.png',
            seventhParam: 'lightning.png',
            eighthParam: '0513x.png',
            shrtInfoView:
                'Stainless steel with textured matte glass back;  A15 Bionic chip  /  6-core CPU / 5-core GPU / 16-core Neural Engine;Pro camera system  /12MP Main /| Ultra Wide | Telephoto |;Superfast 5G cellular;Face ID;Up to 22 hours video playback;Lightning Supports USB 2;Optical zoom options',
            itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
  
        },
        {
            id: 10,
            title: 'MacBook Air 13-in',
            img: 'air_13i_m2.png',
            category: 'MacBook',
            firstParam: 'M3pro.png',
            eighthParam:'touchid.png',
            shrtInfoView:
            '15,3" /Liquid Retina display; 8-core / CPU; 10-core / GPU; Up to / 24GB / unified memory; Up to / 2TB / storage; Up to / 18 hours / battery life; Touch ID ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
        },
 {
            id: 11,
            title: 'MacBook Pro 13-in',
            img: 'pro_13i_m2.png',
            category: 'MacBook',
            firstParam: 'M3pro.png',
            eighthParam:'touchid.png',
            shrtInfoView:
            '15,3" /Liquid Retina display; 8-core / CPU; 10-core / GPU; Up to / 24GB / unified memory; Up to / 2TB / storage; Up to / 18 hours / battery life; Touch ID ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
    },
        {
            id: 12,
            title: 'MacBook Air 15-in',
            img: 'pro_13i_m2.png',
            category: 'MacBook',
            firstParam: 'M3pro.png',
            eighthParam:'touchid.png',
            shrtInfoView:
            '15,3" /Liquid Retina display; 8-core / CPU; 10-core / GPU; Up to / 24GB / unified memory; Up to / 2TB / storage; Up to / 18 hours / battery life; Touch ID ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
        },
        {
            id: 13,
            title: 'MacBook Pro 14-in',
            img: 'Mac14M2Pro.png',
            category: 'MacBook',
            firstParam: 'M3pro.png',
            eighthParam:'touchid.png',
            shrtInfoView:
            '15,3" /Liquid Retina display; 8-core / CPU; 10-core / GPU; Up to / 24GB / unified memory; Up to / 2TB / storage; Up to / 18 hours / battery life; Touch ID ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
        },

        {
            id: 14,
            title: 'MacBook Air 15-in',
            img: 'Mac15M2Air.png',
            category: 'MacBook',
            firstParam: 'M3pro.png',
            eighthParam:'touchid.png',
            shrtInfoView:
            '15,3" /Liquid Retina display; 8-core / CPU; 10-core / GPU; Up to / 24GB / unified memory; Up to / 2TB / storage; Up to / 18 hours / battery life; Touch ID ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
        },
        {
            id: 15,
            title: 'MacBook Pro 16-in',
            img: 'Mac16M3Pro.png',
            category: 'MacBook',
            firstParam: 'M3pro.png',
            eighthParam:'touchid.png',
            shrtInfoView:
            '15,3" /Liquid Retina display; 8-core / CPU; 10-core / GPU; Up to / 24GB / unified memory; Up to / 2TB / storage; Up to / 18 hours / battery life; Touch ID ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 16,
            title: 'Apple Watch Series 9',
            img: 'AppWatS9.png',
            category: 'AppleWatch',
            firstParam: 'size.png',
            secondParam: 'display.png',
            thirdParam: 's9.png',
            fourthParam: 'ecofriendly.png',
            fifthParam: 'network.png',
            sixthParam: 'heartrate.png',
            seventhParam: 'waterresist.png',
            eighthParam: 'battery.png',
            shrtInfoView:
            '49 mm titanium / case size; Always-On / Retina display / Up to 3000 nits; S9 SiP; Carbon neutral; Precision dual-frequency GPS / Celluar connectivity; Blood Oxygen app; Water resistant; Up to 36 hours ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',
   },
        {
            id: 17,
            title: 'Apple Watch Ultra',
            img: 'AppWatUlt.png',
            category: 'AppleWatch',
            firstParam: 'size.png',
            secondParam: 'display.png',
            thirdParam: 's9.png',
            fourthParam: 'ecofriendly.png',
            fifthParam: 'network.png',
            sixthParam: 'heartrate.png',
            seventhParam: 'waterresist.png',
            eighthParam: 'battery.png',
            shrtInfoView:
            '49 mm titanium / case size; Always-On / Retina display / Up to 3000 nits; S9 SiP; Carbon neutral; Precision dual-frequency GPS / Celluar connectivity; Blood Oxygen app; Water resistant; Up to 36 hours ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 18,
            title: 'Apple Watch Ultra',
            img: 'AppWatUlt.png',
            category: 'AppleWatch',
            firstParam: 'size.png',
            secondParam: 'display.png',
            thirdParam: 's9.png',
            fourthParam: 'ecofriendly.png',
            fifthParam: 'network.png',
            sixthParam: 'heartrate.png',
            seventhParam: 'waterresist.png',
            eighthParam: 'battery.png',
            shrtInfoView:
            '49 mm titanium / case size; Always-On / Retina display / Up to 3000 nits; S9 SiP; Carbon neutral; Precision dual-frequency GPS / Celluar connectivity; Blood Oxygen app; Water resistant; Up to 36 hours ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 19,
            title: 'Apple Watch Ultra 2',
            img: 'AppWatUltra2.png',
            category: 'AppleWatch',
            firstParam: 'size.png',
            secondParam: 'display.png',
            thirdParam: 's9.png',
            fourthParam: 'ecofriendly.png',
            fifthParam: 'network.png',
            sixthParam: 'heartrate.png',
            seventhParam: 'waterresist.png',
            eighthParam: 'battery.png',
            shrtInfoView:
            '49 mm titanium / case size; Always-On / Retina display / Up to 3000 nits; S9 SiP; Carbon neutral; Precision dual-frequency GPS / Celluar connectivity; Blood Oxygen app; Water resistant; Up to 36 hours ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 20,
            title: 'AirPods (2-nd gen)',
            img: 'AirPods2g.png',
            category: 'AirPods',
            firstParam: 'doubleTap.png',
            secondParam: 'H1chip.png',
            thirdParam: 'Siri.png',
            fifthParam: 'battery.png',
            sixthParam: 'autoswitch.png',
            seventhParam: 'personalEngraving.png',
            eighthParam: 'chargecase2light.png',
            shrtInfoView:
            'Double tap; H1 Chip; Hey Siri; 5 hrs / Up to 5 hours of listening/ time on one charge; More than 24 hours of / listening time with/ charging case; Automatic Switching; Personalized engraving; Lightning Charging Case ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 21,
            title: 'AirPods Pro (2-nd gen)',
            img: 'AirPodsPro2g.png',
            category: 'AirPods',
            firstParam: 'activeNoiseCancel.png',
            secondParam: 'transparency.png',
            thirdParam: 'staticAudioHeadTracking.png',
            fifthParam: 'battery.png',
            sixthParam: 'H2chip.png',
            seventhParam: 'personalEngraving.png',
            eighthParam: 'chargecase3mag.png',
            shrtInfoView:
            'Double tap; H1 Chip; Hey Siri; 5 hrs / Up to 5 hours of listening/ time on one charge; More than 24 hours of / listening time with/ charging case; Automatic Switching; Personalized engraving; Lightning Charging Case ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 22,
            title: 'AirPods Pro (2-nd gen)',
            img: 'AirPodsPro2g.png',
            category: 'AirPods',
            firstParam: 'doubleTap.png',
            secondParam: 'H1chip.png',
            thirdParam: 'Siri.png',
            fifthParam: 'battery.png',
            sixthParam: 'autoswitch.png',
            seventhParam: 'personalEngraving.png',
            eighthParam: 'chargecase2light.png',
            shrtInfoView:
            'Double tap; H1 Chip; Hey Siri; 5 hrs / Up to 5 hours of listening/ time on one charge; More than 24 hours of / listening time with/ charging case; Automatic Switching; Personalized engraving; Lightning Charging Case ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 23,
            title: 'AirPods Max',
            img: 'AirPodsMax.png',
            category: 'AirPods',
            firstParam: 'activeNoiseCancel.png',
            secondParam: 'transparency.png',
            thirdParam: 'staticAudioHeadTracking.png',
            fifthParam: 'battery.png',
            sixthParam: 'H2chip.png',
            seventhParam: 'personalEngraving.png',
            eighthParam: 'smartcase.png',
            shrtInfoView:
            'Double tap; H1 Chip; Hey Siri; 20 hrs / Up to 20 hours of listening/ time on one charge; More than 24 hours of / listening time with/ charging case; Automatic Switching; Personalized engraving; Lightning Charging Case ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 24,
            title: 'iPad Pro 12.9',
            img: 'ipadpro296thgen.png',
            category: 'Tablet',
            secondParam: 'M2.png',
            thirdParam: 'DualCam.png',
            fourthParam: 'FrontH.png',
            fifthParam: 'ChargePort.png',
            sixthParam: 'Face.png',
            seventhParam: 'quadSpeakers.png',
            eighthParam: 'wifi6.png',
            shrtInfoView:
            '12.9″ / Liquid Retina XDR display/  ProMotion technology / True Tone ; M2 Chip / 8-core CPU/ 10-core GPU; 12MP Wide camera / 10MP Ultra Wide camera / 4k videos, ProRes; 12MP Ultra wide front / camera / Center Stage / TrueDepth; USB-C connector with / support for Thunderbolt; Face ID; Four speaker audio; Wi-Fi speeds up to 2.4 / Gbps ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 25,
            title: 'iPad Pro 11',
            img: 'ipadpro114thgen.png',
            category: 'Tablet',
            secondParam: 'M2.png',
            thirdParam: 'DualCam.png',
            fourthParam: 'FrontH.png',
            fifthParam: 'ChargePort.png',
            sixthParam: 'Face.png',
            seventhParam: 'quadSpeakers.png',
            eighthParam: 'wifi6.png',
            shrtInfoView:
            '11″ / Liquid Retina XDR display/  ProMotion technology / True Tone ; M2 Chip / 8-core CPU/ 10-core GPU; 12MP Wide camera / 10MP Ultra Wide camera / 4k videos, ProRes; 12MP Ultra wide front / camera / Center Stage / TrueDepth; USB-C connector with / support for Thunderbolt; Face ID; Four speaker audio; Wi-Fi speeds up to 2.4 / Gbps ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 26,
            title: 'iPad 10',
            img: 'ipad10thgen.png',
            category: 'Tablet',
            secondParam: 'A14.png',
            thirdParam: 'SingleCam.png',
            fourthParam: 'FrontH.png',
            fifthParam: 'ChargePort.png',
            sixthParam: 'Touch.png',
            seventhParam: 'quadSpeakers.png',
            eighthParam: 'wifi6.png',
            shrtInfoView:
            '10.9″ / Liquid Retina XDR display/  ProMotion technology / True Tone ; M2 Chip / 6-core CPU/ 4-core GPU; 12MP Wide camera  / 4k videos, ProRes; 12MP Ultra wide front / camera / Center Stage / TrueDepth; USB-C connector with / support for Thunderbolt; Touch ID; Four speaker audio; Wi-Fi speeds up to 2.4 / Gbps ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },
        {
            id: 27,
            title: 'iPad 10',
            img: 'ipad10thgen.png',
            category: 'Tablet',
            secondParam: 'A14.png',
            thirdParam: 'SingleCam.png',
            fourthParam: 'FrontH.png',
            fifthParam: 'ChargePort.png',
            sixthParam: 'Touch.png',
            seventhParam: 'quadSpeakers.png',
            eighthParam: 'wifi6.png',
            shrtInfoView:
            '10.9″ / Liquid Retina XDR display/  ProMotion technology / True Tone ; M2 Chip / 6-core CPU/ 4-core GPU; 12MP Wide camera  / 4k videos, ProRes; 12MP Ultra wide front / camera / Center Stage / TrueDepth; USB-C connector with / support for Thunderbolt; Touch ID; Four speaker audio; Wi-Fi speeds up to 2.4 / Gbps ',
        itemsize: ' Height;5.78 inches (146.7 mm);Width;2.82 inches (71.5 mm);Depth;0.30 inch (7.65 mm);Weight;7.19 ounces (204 grams)',

        },


    ]
}
export default items.Data;